### ISSUE TITLE
domain in repo description

### ISSUE THREAD

**Issue by almereyda** [nuest/5starprocessing#1]
It would be nice to have the domain clickable in the repo description.

Also for the https://github.com/nuest/5starprocessing.info/blob/gh-pages/CNAME please consider http://no-www.org/.

**Comment by nuest** [comment]
Clickable URL is done - thanks for the pointer!

Regarding "no www", I did this according to the gh-pages documentation, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages, it is supposed to provide better performance.

http://5starprocessing.info/ does work by redirecting to www.5star...
